language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
addons:
    postgresql: '9.3'
services:
    - redis-sever
install: 
    - "pip install -r requirements/development.txt"
before_script:
    - psql -c 'CREATE DATABASE fastube;' -U postgres
script:
    - pep8 .
    - python fastube/manage.py test users posts
notifications:
  slack: lioliolio:t85FArtn3EjekZRIuT6qvwM0
