language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - "pip install -r requirements/development.txt"
script:
    - pep8 .
    - python fastube/manage.py test users posts
notifications:
  slack: lioliolio:t85FArtn3EjekZRIuT6qvwM0
